# Generated by Django 3.1.7 on 2021-04-06 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Store_id', models.CharField(max_length=50, verbose_name='Store name')),
                ('categories', models.CharField(choices=[('C', 'Coffee'), ('IC', 'Iced Coffee'), ('E', 'Espresso'), ('C', 'Cappucino')], default='C', max_length=2, verbose_name='Categories')),
                ('photo', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=200)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Store_id', models.CharField(max_length=50, verbose_name='Store name')),
                ('categories', models.CharField(choices=[('C', 'Coffee'), ('IC', 'Iced Coffee'), ('E', 'Espresso'), ('C', 'Cappucino')], default='C', max_length=2, verbose_name='Categories')),
                ('photo', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='usersub', to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='1', max_length=1, verbose_name='Rating')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.admin_coffee')),
                ('profile', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='admin_coffee',
            name='favorites',
            field=models.ManyToManyField(to='main_app.Profile'),
        ),
        migrations.AddField(
            model_name='admin_coffee',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='usersubad', to='main_app.profile'),
        ),
    ]
