# Generated by Django 3.1.7 on 2021-04-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210403_1722'),
    ]

    
