# Generated by Django 3.1.7 on 2021-04-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210405_2129'),
    ]
