# Generated by Django 3.1.7 on 2021-04-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210407_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_coffee',
            name='categories',
            field=models.CharField(choices=[('CE', 'Coffee'), ('IC', 'Iced Coffee'), ('E', 'Espresso'), ('CA', 'Cappucino')], default='CE', max_length=2, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='user_coffee',
            name='categories',
            field=models.CharField(choices=[('CE', 'Coffee'), ('IC', 'Iced Coffee'), ('E', 'Espresso'), ('CA', 'Cappucino')], default='CE', max_length=2, verbose_name='Categories'),
        ),
    ]
