# Generated by Django 3.1.7 on 2021-04-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210408_1419'),
        ('main_app', '0008_auto_20210408_1236'),
    ]

    operations = [
    ]
