# Generated by Django 3.1.7 on 2021-04-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20210408_2049'),
        ('main_app', '0011_auto_20210408_2055'),
    ]

    operations = [
    ]
