# Generated by Django 3.1.7 on 2021-04-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20210408_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_coffee',
            name='categories',
            field=models.CharField(max_length=20, verbose_name='Categories'),
        ),
    ]
