# Generated by Django 3.1.7 on 2021-04-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210408_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_coffee',
            name='categories',
            field=models.CharField(max_length=20, verbose_name='Categories'),
        ),
    ]
