# Generated by Django 3.1.7 on 2021-04-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210408_2300'),
        ('main_app', '0012_merge_20210408_2258'),
    ]

    operations = [
    ]
