# Generated by Django 3.1.7 on 2021-04-09 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_merge_20210408_2315'),
        ('main_app', '0015_merge_20210408_2317'),
    ]

    operations = [
    ]
